### ISSUE TITLE
同在学习Soot

### ISSUE THREAD

**Issue by xwlin-roy** [2048li/Soottest#1]
你好，关注到你在利用Soot进行APK分析，插桩。我目前也在做这个研究，但因为是新手，还没入门。之前到你新浪博客发过私信，但新浪博客有问题，信息刷新就没了。所以在github这里联系你，是否可以加你QQ或者微信，一起交流呢？

**Comment by 2048li** [comment]
你好同学。若该project你已经克隆，请删除本地文件。谢谢合作。
可以。发邮件就好。

**Comment by xwlin-roy** [comment]
没有clone，好的，看到你的邮箱了。

**Comment by 2048li** [comment]
请看我git主页。
